Repository form-maker/FFF-BE, pull requests merged in 2023-02, with the labels that each got.

#204 ♻️ Refactor: 아이디 중복체크 수정
  src/main/java/com/formmaker/fff/user/controller/UserController.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#206 ♻️ Refactor 서술형 응답 글자수 500 자로 변경
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
Labels: refactoring

#209 ♻️Refactor : 설문 상태 업데이트 로직 수정
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java
Labels: refactoring

#214 ♻️Refactor : uri 오픈
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
Labels: refactoring

#211 ♻️ Refactor : 이메일 형식의 값이 아닐 때, 인증번호 발송 실패 응답 발송하도록 에러처리
  src/main/java/com/formmaker/fff/mail/controller/MailController.java
  src/main/java/com/formmaker/fff/mail/service/MailService.java
Labels: refactoring

#212 ✨ Feat: 설문 문제 필수응답 유무 체크
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
  src/main/java/com/formmaker/fff/question/entity/Question.java
  src/main/java/com/formmaker/fff/question/service/QuestionService.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: enhancement

#215 ♻️ Refactor: 설문 조회시 전체 응답자 표기
  src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
  src/main/java/com/formmaker/fff/question/service/QuestionService.java
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyReadResponse.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#216 ♻️ Refactor : Survey -> User 단방향 연관관계 설정과 그에 따라 코드 수정
  src/main/java/com/formmaker/fff/mail/service/MailService.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#218 ♻️ Refactor: 설문 제작시 설문 타이틀 및 설명 유효성 검사 , 문항 유무 유효성 검사
  src/main/java/com/formmaker/fff/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/formmaker/fff/common/exception/CustomValidException.java
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/exception/GlobalExceptionHandler.java
  src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/question/entity/Question.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/dto/request/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#221 ♻️ Refactor: 리프레쉬토큰 수정
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/user/controller/RefreshController.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#233 ✨Feat : slide 통계 라벨추가
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
Labels: enhancement

#231 Refactor/#230
  src/main/java/com/formmaker/fff/common/aop/timer/ExeTimer.java
  src/main/java/com/formmaker/fff/common/aop/timer/ExecutionTimer.java
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/user/controller/RefreshController.java
Labels: enhancement, refactoring

#235 ♻️ Refactorr : email 을 조회할 때, Jpql Join 을 사용한 조회로 로직 변경
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/mail/service/MailService.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
Labels: refactoring

#237 ♻️Refactor : SSE API 통합
  src/main/java/com/formmaker/fff/common/aop/timer/ExecutionTimer.java
  src/main/java/com/formmaker/fff/sse/controller/SseController.java
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
Labels: refactoring

#236 ♻️ Refactor: 응답시 update문 발생 수정
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
Labels: refactoring

#239 ♻️Refactor : 헤더 추가
  src/main/java/com/formmaker/fff/sse/controller/SseController.java
Labels: refactoring

#242 ♻️Refactor : 주석 제거 및 코드 삭제
  src/main/java/com/formmaker/fff/answer/repositoy/AnswerRepository.java
  src/main/java/com/formmaker/fff/common/aop/timer/ExecutionTimer.java
  src/main/java/com/formmaker/fff/common/config/SwaggerConfig.java
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/exception/GlobalExceptionHandler.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/common/redis/RedisUtil.java
  src/main/java/com/formmaker/fff/common/response/security/UserDetailsServiceImpl.java
  src/main/java/com/formmaker/fff/mail/service/MailService.java
  src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
  src/main/java/com/formmaker/fff/question/repository/QuestionRepository.java
  src/main/java/com/formmaker/fff/question/service/QuestionService.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepository.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
  src/main/java/com/formmaker/fff/user/controller/RefreshController.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
  src/main/java/com/formmaker/fff/user/dto/request/SocialUserInfoDto.java
  src/main/java/com/formmaker/fff/user/dto/request/UserSignupRequest.java
  src/main/java/com/formmaker/fff/user/entity/User.java
  src/main/java/com/formmaker/fff/user/service/GoogleService.java
  src/main/java/com/formmaker/fff/user/service/KakaoService.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#243 ♻️ Refactor: 설문 삭제 로직 수정
  src/main/java/com/formmaker/fff/answer/repositoy/AnswerRepository.java
  src/main/java/com/formmaker/fff/gift/giftRepository/GiftRepository.java
  src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
  src/main/java/com/formmaker/fff/question/repository/QuestionRepository.java
  src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring
