Repository form-maker/FFF-BE, pull requests merged in 2023-01, with the labels that each got.

#5 ✨ feat: 기본 회원가입 구현
  src/main/java/com/formmaker/fff/common/response/ResponseMessage.java
  src/main/java/com/formmaker/fff/user/User.java
  src/main/java/com/formmaker/fff/user/UserController.java
  src/main/java/com/formmaker/fff/user/UserRepository.java
  src/main/java/com/formmaker/fff/user/UserService.java
  src/main/java/com/formmaker/fff/user/request/UserSignupRequest.java
Labels: enhancement

#7 ✨Feat: 로그인아이디 중복확인 구현
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/user/UserController.java
  src/main/java/com/formmaker/fff/user/UserRepository.java
  src/main/java/com/formmaker/fff/user/UserService.java
Labels: enhancement

#9 ✨Feat: 유저닉네임 중복확인 구현
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/user/UserController.java
  src/main/java/com/formmaker/fff/user/UserRepository.java
  src/main/java/com/formmaker/fff/user/UserService.java
Labels: enhancement

#12 ✨Feat : 설문 생성 구현
  src/main/java/com/formmaker/fff/answer/Answer.java
  src/main/java/com/formmaker/fff/answer/AnswerCreateRequestDto.java
  src/main/java/com/formmaker/fff/answer/AnswerRepository.java
  src/main/java/com/formmaker/fff/common/response/ResponseMessage.java
  src/main/java/com/formmaker/fff/question/Question.java
  src/main/java/com/formmaker/fff/question/QuestionCreateRequestDto.java
  src/main/java/com/formmaker/fff/question/QuestionRepository.java
  src/main/java/com/formmaker/fff/survey/Survey.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
  src/main/resources/application.properties
Labels: enhancement

#14 ✨Feat : 로그인 API 구현
  build.gradle
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/user/UserController.java
  src/main/java/com/formmaker/fff/user/UserService.java
  src/main/java/com/formmaker/fff/user/request/UserLoginRequest.java
  src/main/resources/application.properties
Labels: enhancement

#16 ♻️Refactor: properties 복구
  .gitignore
  src/main/resources/application.properties
Labels: refactoring

#17 ✨ Feat : CI/CD 환경 설정
  .github/workflows/gradle.yml
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
Labels: enhancement

#19 ♻️ Refactor : CI/CD 리팩토링
  .github/workflows/gradle.yml
Labels: refactoring

#20 ✨Feat: security 기능 추가 및 적용
  build.gradle
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/exception/GlobalExceptionHandler.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/common/jwt/exception/CustomSecurityException.java
  src/main/java/com/formmaker/fff/common/jwt/exception/JwtExceptionHandlerFilter.java
  src/main/java/com/formmaker/fff/common/security/UserDetailsImpl.java
  src/main/java/com/formmaker/fff/common/security/UserDetailsServiceImpl.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/user/UserService.java
Labels: enhancement

#23 ♻️ Refactor : git action 시크릿 프로퍼티 설정 추가
  .github/workflows/gradle.yml
Labels: refactoring

#21 ✨ Feat : 메인페이지 설문 조회 구현
  src/main/java/com/formmaker/fff/FffApplication.java
  src/main/java/com/formmaker/fff/answer/request/AnswerCreateRequest.java
  src/main/java/com/formmaker/fff/common/TimeStamped.java
  src/main/java/com/formmaker/fff/common/response/DataPageResponse.java
  src/main/java/com/formmaker/fff/common/response/PageStatusResponse.java
  src/main/java/com/formmaker/fff/common/type/SortTypeEnum.java
  src/main/java/com/formmaker/fff/question/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/survey/Survey.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
  src/main/java/com/formmaker/fff/survey/request/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/response/SurveyMainResponse.java
Labels: enhancement

#25 🐛Fix : 패키지 오류 수정
  src/main/java/com/formmaker/fff/survey/SurveyController.java
Labels: bug

#29 ✨Feat: 설문 삭제 API 구현
  src/main/java/com/formmaker/fff/answer/AnswerRepository.java
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/question/QuestionRepository.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
Labels: enhancement

#32 ✨ Feat : 선택 설문 조회 API
  src/main/java/com/formmaker/fff/question/QuestionRepository.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
  src/main/java/com/formmaker/fff/survey/response/SurveySpecificResponse.java
Labels: enhancement

#36 ✨ Feat : 설문 문항 조회 API
  src/main/java/com/formmaker/fff/answer/Answer.java
  src/main/java/com/formmaker/fff/question/QuestionRepository.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
  src/main/java/com/formmaker/fff/survey/response/AnswerResponse.java
  src/main/java/com/formmaker/fff/survey/response/QuestionSpecificResponse.java
Labels: enhancement

#42 ✨Feat : 카카오 로그인 구현
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/type/SocialTypeEnum.java
  src/main/java/com/formmaker/fff/user/OauthService.java
  src/main/java/com/formmaker/fff/user/User.java
  src/main/java/com/formmaker/fff/user/UserController.java
  src/main/java/com/formmaker/fff/user/UserRepository.java
Labels: enhancement

#43 ✨Feat: 마이페이지 조회 기능
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
  src/main/java/com/formmaker/fff/survey/response/SurveyMyResponse.java
Labels: enhancement

#44 ✨ Feat : 설문 응답 등록 API 구현
  src/main/java/com/formmaker/fff/reply/Reply.java
  src/main/java/com/formmaker/fff/reply/ReplyRepository.java
  src/main/java/com/formmaker/fff/reply/ReplyService.java
  src/main/java/com/formmaker/fff/survey/SurveyController.java
  src/main/java/com/formmaker/fff/survey/SurveyService.java
  src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
  src/main/java/com/formmaker/fff/survey/request/ReplyRequest.java
Labels: enhancement

#56 ✨Feat : 설문 상태 컬럼 수정
  src/main/java/com/formmaker/fff/common/type/AnswerTypeEnum.java
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/common/type/StatusTypeEnum.java
  src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/request/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/response/SurveyMainResponse.java
  src/main/java/com/formmaker/fff/survey/response/SurveyMyResponse.java
  src/main/java/com/formmaker/fff/survey/response/SurveyReadResponse.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#57 ♻️ Refactor : 설문 시작 지점 수정
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/type/StatusTypeEnum.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/request/ReplyCreateRequest.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/request/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/response/SurveyMainResponse.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#58 ♻️ Refactor : 질문 응답 값에 대한 컬럼 변경
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
Labels: refactoring

#61 ♻️Refactor : 설문 문제 컬럼 변경
  src/main/java/com/formmaker/fff/answer/entity/Answer.java
  src/main/java/com/formmaker/fff/answer/request/AnswerCreateRequest.java
  src/main/java/com/formmaker/fff/answer/response/AnswerResponse.java
  src/main/java/com/formmaker/fff/question/controller/QuestionController.java
  src/main/java/com/formmaker/fff/question/entity/Question.java
  src/main/java/com/formmaker/fff/question/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/question/response/QuestionResponse.java
  src/main/java/com/formmaker/fff/question/service/QuestionService.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#59 ✨Feat: 구글 로그인 구현
  build.gradle
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/type/SocialTypeEnum.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
  src/main/java/com/formmaker/fff/user/entity/User.java
  src/main/java/com/formmaker/fff/user/request/SocialUserInfoDto.java
  src/main/java/com/formmaker/fff/user/service/GoogleService.java
Labels: enhancement

#60 ✨ Feat : 토큰 확인 기능 추가
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/common/jwt/exception/CustomSecurityException.java
  src/main/java/com/formmaker/fff/common/jwt/exception/JwtExceptionHandlerFilter.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
Labels: enhancement

#62 ♻️Refactor : 설문 조회 수정
  src/main/java/com/formmaker/fff/common/type/SortTypeEnum.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#67 ♻️ Refactor : Entity 대신 Entity Dto 를 사용하도록 로직 변경
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#74 ♻️Refactor : 설문 생성 수정
  src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/question/entity/Question.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#76 ✨Feat : 설문 통계 기초 틀
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/dto/DailyParticipant.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
  src/main/java/com/formmaker/fff/stats/dto/StatsResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement

#80 ✨Feat : 자정 설문 상태 업데이트 기능 추가
  src/main/java/com/formmaker/fff/FffApplication.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java
Labels: enhancement

#81 ✨Feat: 통계조회 MultipleChoice API 구현
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement

#85 ♻️ Refactor : Reply Entity 컬럼 수정 및 내부로직 변경
  build.gradle
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
  src/main/java/com/formmaker/fff/reply/dto/request/ReplyCreateRequest.java
  src/main/java/com/formmaker/fff/reply/dto/request/ReplyDto.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: refactoring

#89 ♻️ Refactor : Reply 저장 로직 수정
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/question/dto/QuestionDto.java
  src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
  src/main/java/com/formmaker/fff/reply/dto/ReplyDto.java
  src/main/java/com/formmaker/fff/reply/dto/request/EachReplyRequest.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#88 ♻️Refactor: 통계조회 Single,MultipleChoice API통합
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
Labels: refactoring

#91 ✨ Feat : 설문 통계 조회 - 별점, Score
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement

#93 ✨Feat : 실시간 참가 인원 조회 기능 추가
  build.gradle
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/sse/CustomEmitter.java
  src/main/java/com/formmaker/fff/sse/controller/SseController.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepository.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
Labels: enhancement

#95 ✨Feat: 설문 통계 조회 슬라이드 API
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
Labels: enhancement

#96 ✨Feat: shortDescriptive 통계 조회 API 구현
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/DescriptiveResponse.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
Labels: enhancement

#97 ✨Feat : 설문 응답 파일 다운로드 기능 추가
  build.gradle
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement

#104 ♻️Refactor : 메인페이지 필드 추가
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyMainResponse.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#106 ✨ Feat : 랭크 통계 API 작성
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
  src/main/java/com/formmaker/fff/stats/dto/StatsResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/resources/application.properties
Labels: enhancement

#105 ♻️Refactor : 마이 페이지 필드 수정
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyMyResponse.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#107 ♻️Refactor
  src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
  src/main/java/com/formmaker/fff/reply/dto/request/ReplyRequest.java
  src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
Labels: refactoring

#110 ♻️ Refactor : EntityDto 삭제 및 그에 따른 변경사항 적용
  build.gradle
  src/main/java/com/formmaker/fff/answer/dto/AnswerDto.java
  src/main/java/com/formmaker/fff/question/dto/QuestionDto.java
  src/main/java/com/formmaker/fff/question/service/QuestionService.java
  src/main/java/com/formmaker/fff/reply/dto/ReplyDto.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/survey/dto/SurveyDto.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
  src/main/java/com/formmaker/fff/user/dto/UserDto.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#112 ♻️Refactor : 통계 코드 최적화
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
Labels: refactoring

#116 ✨Feat: 유효성 검사 추가
  build.gradle
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/exception/GlobalExceptionHandler.java
  src/main/java/com/formmaker/fff/common/response/ValidMessageResponse.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
  src/main/java/com/formmaker/fff/user/dto/request/UserSignupRequest.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: enhancement

#114 ✨Feat : 날짜별 참가자 수 통계 기능 추가
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/stats/dto/DailyParticipant.java
  src/main/java/com/formmaker/fff/stats/dto/StatsResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement

#117 ✨Feat : 설문 주관식 장문형 조회 기능 추가
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/DescriptiveResponse.java
Labels: enhancement

#119 ✨Feat : 날짜별 통계 조회 기능 추가
  src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement

#122 ♻️ Refactor: 설문 조회 필드 추가
  src/main/java/com/formmaker/fff/question/dto/response/QuestionResponse.java
  src/main/java/com/formmaker/fff/question/service/QuestionService.java
Labels: refactoring

#123 ✨ Feat : 이메일 인증 API 구현
  build.gradle
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/mail/config/MailConfig.java
  src/main/java/com/formmaker/fff/mail/controller/MailController.java
  src/main/java/com/formmaker/fff/mail/entity/EmailAuth.java
  src/main/java/com/formmaker/fff/mail/repository/EmailAuthRepository.java
  src/main/java/com/formmaker/fff/mail/service/MailService.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: enhancement

#127 ♻️Refactor : MyPage Response 수정
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/dto/response/MyPageResponse.java
Labels: refactoring

#135 ♻️Refactor : url 허용 수정
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/response/security/UserDetailsImpl.java
  src/main/java/com/formmaker/fff/common/response/security/UserDetailsServiceImpl.java
Labels: refactoring

#136 ✨Feat : 설문 참가 테이블 추가
  src/main/java/com/formmaker/fff/participant/Participant.java
  src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/repository/ReplyRepository.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
Labels: enhancement, refactoring

#141 ✨ Feat : 로컬에서 레디스를 통한 이메일 인증 기능 구현
  src/main/java/com/formmaker/fff/common/redis/RedisConfig.java
  src/main/java/com/formmaker/fff/common/redis/RedisUtil.java
  src/main/java/com/formmaker/fff/mail/entity/EmailAuth.java
  src/main/java/com/formmaker/fff/mail/repository/EmailAuthRepository.java
  src/main/java/com/formmaker/fff/mail/service/MailService.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: enhancement

#142 ✨Feat: RefreshToken 구현
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/common/jwt/RefreshToken.java
  src/main/java/com/formmaker/fff/common/jwt/RefreshTokenRepository.java
  src/main/java/com/formmaker/fff/common/jwt/TokenDto.java
  src/main/java/com/formmaker/fff/user/controller/RefreshController.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
  src/main/java/com/formmaker/fff/user/service/GoogleService.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: enhancement

#145 ♻️ Refactor : 회원가입 성공 시, 만료시간이 지나지않은 인증코드 redis 에서 삭제
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#143 ♻️Refactor : SSE 로직 개선
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/sse/CustomEmitter.java
  src/main/java/com/formmaker/fff/sse/controller/SseController.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepository.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
Labels: refactoring

#148 ♻️Refactor: 삭제 타입 변경으로, 변경
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/type/StatusTypeEnum.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#154 ♻️Refactor : sse 객체 유효성 검사
  build.gradle
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
Labels: refactoring

#156 ♻️Refactor : SSE 응답 데이터 Json화 및 오류 수정
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
  src/main/java/com/formmaker/fff/user/service/GoogleService.java
  src/main/java/com/formmaker/fff/user/service/KakaoService.java
Labels: bug, refactoring

#158 ♻️ Refactor : 헤더에 담긴 리프레쉬 토큰에 접근할 수 있도록 설정
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
Labels: refactoring

#153 ♻️Refactor: 리프레쉬 토큰 레디스 적용
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/common/redis/RedisUtil.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#159 ♻️Refactor : Sse API 분리
  src/main/java/com/formmaker/fff/sse/CustomEmitter.java
  src/main/java/com/formmaker/fff/sse/controller/SseController.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepository.java
  src/main/java/com/formmaker/fff/sse/repository/EmitterRepositoryImpl.java
  src/main/java/com/formmaker/fff/sse/service/NotificationService.java
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyMainResponse.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#163 ♻️ Refactor: 허가수정
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
Labels: refactoring

#165 ♻️ Refactor : certbot 요청 인가 거절 이슈 - 방안1
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
Labels: refactoring

#149 ♻️Refactor : 설문 생성 유효성 검사
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/question/dto/request/QuestionCreateRequest.java
  src/main/java/com/formmaker/fff/question/entity/Question.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: refactoring

#166 ♻️Refactor : 통계 개선
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/dto/SelectResponse.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: refactoring

#169 ✨Feat : 설문 응답 질문 정보 추가
  src/main/java/com/formmaker/fff/question/dto/response/QuestionNavigationResponse.java
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyReadResponse.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
Labels: enhancement

#171 ♻️Refactor: 엑세스토큰 시간수정
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
Labels: refactoring

#174 ✨Feat : 선물 폼 추가
  src/main/java/com/formmaker/fff/gift/dto/request/GiftCreateRequest.java
  src/main/java/com/formmaker/fff/gift/dto/response/GiftResponse.java
  src/main/java/com/formmaker/fff/gift/entity/Gift.java
  src/main/java/com/formmaker/fff/gift/giftRepository/GiftRepository.java
  src/main/java/com/formmaker/fff/survey/controller/SurveyController.java
  src/main/java/com/formmaker/fff/survey/dto/request/SurveyCreateRequest.java
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyMainResponse.java
  src/main/java/com/formmaker/fff/survey/dto/response/SurveyReadResponse.java
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
Labels: enhancement, refactoring

#173 ✨Feat : 비회원 설문 응답 로직 추가
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/common/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/common/response/security/UserDetailsImpl.java
  src/main/java/com/formmaker/fff/participant/Participant.java
  src/main/java/com/formmaker/fff/participant/ParticipantRepository.java
  src/main/java/com/formmaker/fff/reply/controller/ReplyController.java
  src/main/java/com/formmaker/fff/reply/entity/Reply.java
  src/main/java/com/formmaker/fff/reply/service/ReplyMethod.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyService.java
  src/main/java/com/formmaker/fff/user/repository/UserRepository.java
Labels: enhancement, refactoring

#179 ♻️ Refactor : 주관식 서술형, 전체 응답 데이터 반환로직 추가
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/DescriptiveList.java
  src/main/java/com/formmaker/fff/stats/dto/QuestionStats.java
Labels: refactoring

#181 ♻️ Refactor : https 프론트 도메인 cors 설정
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
Labels: refactoring

#183 ♻️ Refactor: 단답형 수정
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/dto/DescriptiveList.java
Labels: refactoring

#185 ♻️ Refactor : D-Day 컬럼 삭제 및 D-Day 계산 로직 추가
  src/main/java/com/formmaker/fff/survey/entity/Survey.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
  src/main/java/com/formmaker/fff/survey/service/SurveyScheduler.java
Labels: refactoring

#186 ✨Feat : xlsx 다운로드 기능 추가
  build.gradle
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
Labels: enhancement, refactoring

#187 ♻️Refactor : 다운로드 권한 변경
  src/main/java/com/formmaker/fff/common/config/WebSecurityConfig.java
  src/main/java/com/formmaker/fff/stats/controller/StatsController.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: refactoring

#189 ♻️Refactor : JWT 인증 방식 수정
  src/main/java/com/formmaker/fff/common/jwt/JwtAuthFilter.java
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
  src/main/java/com/formmaker/fff/user/controller/UserController.java
Labels: refactoring

#192 ♻️Refactor : 정렬 수정 및 저장 오류 수정
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: bug, refactoring

#194 ♻️ Refactor: 토큰 시간 수정
  src/main/java/com/formmaker/fff/common/jwt/JwtUtil.java
Labels: refactoring

#198 ♻️Refactor : 평균 소숫점, refreshToken 삭제
  src/main/java/com/formmaker/fff/common/jwt/RefreshToken.java
  src/main/java/com/formmaker/fff/common/jwt/RefreshTokenRepository.java
  src/main/java/com/formmaker/fff/common/jwt/TokenDto.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/user/service/UserService.java
Labels: refactoring

#195 ✨ Feat : 마감된 설문 안내 메일 발송
  src/main/java/com/formmaker/fff/common/exception/ErrorCode.java
  src/main/java/com/formmaker/fff/mail/controller/MailController.java
  src/main/java/com/formmaker/fff/mail/service/MailService.java
  src/main/java/com/formmaker/fff/survey/repository/SurveyRepository.java
Labels: enhancement

#200 ✨Feat : 동의 폼 추가
  src/main/java/com/formmaker/fff/common/type/QuestionTypeEnum.java
  src/main/java/com/formmaker/fff/reply/service/ReplyService.java
  src/main/java/com/formmaker/fff/stats/StatsMethod.java
  src/main/java/com/formmaker/fff/stats/service/StatsService.java
Labels: enhancement
